fn main() {
    let output = generate_typescript();
    std::fs::write("../desktop/src/generated/models.ts", output)
        .expect("failed to write typescript");
}

fn generate_typescript() -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by runebound-models build script\n");
    out.push_str("// Do not edit manually - changes will be overwritten\n\n");

    out.push_str("export type NpcDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  race: string;\n");
    out.push_str("  occupation: string;\n");
    out.push_str("  sex: string;\n");
    out.push_str("  age: string;\n");
    out.push_str("  height: string;\n");
    out.push_str("  weight_lbs: string;\n");
    out.push_str("  background: string;\n");
    out.push_str("  want_need: string;\n");
    out.push_str("  secret_obstacle: string;\n");
    out.push_str("  carrying: string[];\n");
    out.push_str("  location: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type LocationDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  kind_type: string;\n");
    out.push_str("  kind_custom?: string | null;\n");
    out.push_str("  visual_description: string;\n");
    out.push_str("  history_background: string;\n");
    out.push_str("  exports: string[];\n");
    out.push_str("  tone: string;\n");
    out.push_str("  authority: string;\n");
    out.push_str("  danger_level: string;\n");
    out.push_str("  current_tension: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type FactionDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  kind_type: string;\n");
    out.push_str("  kind_custom?: string | null;\n");
    out.push_str("  public_description: string;\n");
    out.push_str("  true_agenda: string;\n");
    out.push_str("  methods: string;\n");
    out.push_str("  leadership: string;\n");
    out.push_str("  headquarters: string;\n");
    out.push_str("  sphere_of_influence: string;\n");
    out.push_str("  resources_assets: string;\n");
    out.push_str("  allies: string[];\n");
    out.push_str("  rivals_enemies: string[];\n");
    out.push_str("  reputation: string;\n");
    out.push_str("  current_tension: string;\n");
    out.push_str("  goals_short_term: string[];\n");
    out.push_str("  goals_long_term: string[];\n");
    out.push_str("  symbol_description: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type ItemDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  category: string;\n");
    out.push_str("  rarity: string;\n");
    out.push_str("  attunement: string;\n");
    out.push_str("  materials: string[];\n");
    out.push_str("  appearance: string;\n");
    out.push_str("  abilities: string;\n");
    out.push_str("  drawbacks: string;\n");
    out.push_str("  history: string;\n");
    out.push_str("  value: string;\n");
    out.push_str("  location: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type EventDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  body: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type GodDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  epithet: string;\n");
    out.push_str("  rank: string;\n");
    out.push_str("  rank_custom?: string | null;\n");
    out.push_str("  alignment: string;\n");
    out.push_str("  domains: string[];\n");
    out.push_str("  symbol: string;\n");
    out.push_str("  appearance: string;\n");
    out.push_str("  dogma: string;\n");
    out.push_str("  realm: string;\n");
    out.push_str("  worshippers: string;\n");
    out.push_str("  clergy: string;\n");
    out.push_str("  allies: string[];\n");
    out.push_str("  rivals: string[];\n");
    out.push_str("};\n\n");

    out.push_str("export type DungeonBeat = {\n");
    out.push_str("  function: string;\n");
    out.push_str("  content_type: string;\n");
    out.push_str("  idea: string;\n");
    out.push_str("  player_goals: string;\n");
    out.push_str("  lever: string;\n");
    out.push_str("  loot?: string | null;\n");
    out.push_str("  design_note: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type DungeonDraft = {\n");
    out.push_str("  id: string;\n");
    out.push_str("  seed_prompt?: string | null;\n");
    out.push_str("  name: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  location: string;\n");
    out.push_str("  story: string;\n");
    out.push_str("  premise: string;\n");
    out.push_str("  topology: string;\n");
    out.push_str("  tone: string;\n");
    out.push_str("  twist: string;\n");
    out.push_str("  beats: DungeonBeat[];\n");
    out.push_str("};\n\n");

    out.push_str("export type NpcFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  race: string;\n");
    out.push_str("  occupation: string;\n");
    out.push_str("  sex: string;\n");
    out.push_str("  age: string;\n");
    out.push_str("  height: string;\n");
    out.push_str("  weight_lbs: string;\n");
    out.push_str("  background: string;\n");
    out.push_str("  want_need: string;\n");
    out.push_str("  secret_obstacle: string;\n");
    out.push_str("  carrying: string[];\n");
    out.push_str("  location: string;\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type LocationFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  kind_type: string;\n");
    out.push_str("  kind_custom?: string | null;\n");
    out.push_str("  visual_description: string;\n");
    out.push_str("  history_background: string;\n");
    out.push_str("  exports: string[];\n");
    out.push_str("  tone: string;\n");
    out.push_str("  authority: string;\n");
    out.push_str("  danger_level: string;\n");
    out.push_str("  current_tension: string;\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type FactionFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  kind_type: string;\n");
    out.push_str("  kind_custom?: string | null;\n");
    out.push_str("  public_description: string;\n");
    out.push_str("  true_agenda: string;\n");
    out.push_str("  methods: string;\n");
    out.push_str("  leadership: string;\n");
    out.push_str("  headquarters: string;\n");
    out.push_str("  sphere_of_influence: string;\n");
    out.push_str("  resources_assets: string;\n");
    out.push_str("  allies: string[];\n");
    out.push_str("  rivals_enemies: string[];\n");
    out.push_str("  reputation: string;\n");
    out.push_str("  current_tension: string;\n");
    out.push_str("  goals_short_term: string[];\n");
    out.push_str("  goals_long_term: string[];\n");
    out.push_str("  symbol_description: string;\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type ItemFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  category: string;\n");
    out.push_str("  rarity: string;\n");
    out.push_str("  attunement: string;\n");
    out.push_str("  materials: string[];\n");
    out.push_str("  appearance: string;\n");
    out.push_str("  abilities: string;\n");
    out.push_str("  drawbacks: string;\n");
    out.push_str("  history: string;\n");
    out.push_str("  value: string;\n");
    out.push_str("  location: string;\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type GodFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  epithet: string;\n");
    out.push_str("  rank: string;\n");
    out.push_str("  rank_custom?: string | null;\n");
    out.push_str("  alignment: string;\n");
    out.push_str("  domains: string[];\n");
    out.push_str("  symbol: string;\n");
    out.push_str("  appearance: string;\n");
    out.push_str("  dogma: string;\n");
    out.push_str("  realm: string;\n");
    out.push_str("  worshippers: string;\n");
    out.push_str("  clergy: string;\n");
    out.push_str("  allies: string[];\n");
    out.push_str("  rivals: string[];\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type DungeonFrontmatter = {\n");
    out.push_str("  type: string;\n");
    out.push_str("  id: string;\n");
    out.push_str("  slug: string;\n");
    out.push_str("  name: string;\n");
    out.push_str("  vault_path: string;\n");
    out.push_str("  premise: string;\n");
    out.push_str("  topology: string;\n");
    out.push_str("  tone: string;\n");
    out.push_str("  twist: string;\n");
    out.push_str("  beats: DungeonBeat[];\n");
    out.push_str("  created_at: string;\n");
    out.push_str("  updated_at: string;\n");
    out.push_str("  published_at?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type EntityCardRow = {\n");
    out.push_str("  label: string;\n");
    out.push_str("  value: string;\n");
    out.push_str("};\n\n");

    out.push_str("export type InlineNode =\n");
    out.push_str("  | { kind: \"text\"; text: string }\n");
    out.push_str("  | { kind: \"command_ref\"; label: string; command: string }\n");
    out.push_str("  | { kind: \"emphasis\"; text: string }\n");
    out.push_str("  | { kind: \"strong\"; text: string }\n");
    out.push_str("  | { kind: \"code\"; text: string };\n\n");

    out.push_str("export type StatusTone = \"success\" | \"info\" | \"warning\" | \"error\";\n\n");

    out.push_str("export type SpinnerState = \"running\" | \"success\" | \"error\";\n\n");

    out.push_str("export type OutputBlock =\n");
    out.push_str("  | { kind: \"heading\"; level: number; text: string }\n");
    out.push_str("  | { kind: \"paragraph\"; inlines: InlineNode[] }\n");
    out.push_str("  | { kind: \"list\"; items: InlineNode[][] }\n");
    out.push_str("  | { kind: \"code\"; language?: string | null; text: string }\n");
    out.push_str("  | { kind: \"status\"; tone: StatusTone; text: string }\n");
    out.push_str("  | { kind: \"spinner\"; state: SpinnerState; text: string }\n");
    out.push_str("  | { kind: \"entity_card\"; title: string; rows: EntityCardRow[] }\n");
    out.push_str("  | { kind: \"image\"; src: string; alt: string };\n\n");

    out.push_str("export type OutputDoc = {\n");
    out.push_str("  blocks: OutputBlock[];\n");
    out.push_str("};\n\n");

    out.push_str("export type OutputSegmentKind = \"text\" | \"error\";\n\n");

    out.push_str("export type OutputSegment = {\n");
    out.push_str("  kind: OutputSegmentKind;\n");
    out.push_str("  text: string;\n");
    out.push_str("  command_ref?: string | null;\n");
    out.push_str("};\n\n");

    out.push_str("export type CommandClientEvent =\n");
    out.push_str(
        "  | { kind: \"load_npc_draft_with_card\"; draft: NpcDraft; entity_card: OutputDoc }\n",
    );
    out.push_str("  | { kind: \"load_location_draft_with_card\"; draft: LocationDraft; entity_card: OutputDoc }\n");
    out.push_str("  | { kind: \"load_faction_draft_with_card\"; draft: FactionDraft; entity_card: OutputDoc }\n");
    out.push_str(
        "  | { kind: \"load_item_draft_with_card\"; draft: ItemDraft; entity_card: OutputDoc }\n",
    );
    out.push_str(
        "  | { kind: \"load_event_draft_with_card\"; draft: EventDraft; entity_card: OutputDoc }\n",
    );
    out.push_str(
        "  | { kind: \"load_god_draft_with_card\"; draft: GodDraft; entity_card: OutputDoc }\n",
    );
    out.push_str("  | { kind: \"load_dungeon_draft_with_card\"; draft: DungeonDraft; entity_card: OutputDoc }\n");
    out.push_str("  | { kind: \"clear_drafts\" }\n");
    out.push_str("  | { kind: \"clear_terminal\"; clear_history: boolean }\n");
    out.push_str("  | { kind: \"exit_requested\" };\n\n");

    out.push_str("export type CommandResponse = {\n");
    out.push_str("  ok: boolean;\n");
    out.push_str("  output: string;\n");
    out.push_str("  error?: string | null;\n");
    out.push_str("  exit_code: number;\n");
    out.push_str("  segments?: OutputSegment[];\n");
    out.push_str("  output_doc?: OutputDoc | null;\n");
    out.push_str("  client_event?: CommandClientEvent | null;\n");
    out.push_str("};\n\n");

    out
}
