ALTER TABLE npcs ADD COLUMN age TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE npcs ADD COLUMN height TEXT NOT NULL DEFAULT 'Unknown';
ALTER TABLE npcs ADD COLUMN weight_lbs TEXT NOT NULL DEFAULT 'Unknown';
