use std::path::Path;

use chrono::Utc;
use serde::Serialize;

pub const UNKNOWN_LOCATION: &str = "Unknown";

#[derive(Debug, Clone, Serialize)]
pub struct NpcFrontmatter {
    pub doc_type: String,
    pub id: String,
    pub slug: String,
    pub name: String,
    pub race: String,
    pub sex: String,
    pub location: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct LocationFrontmatter {
    pub doc_type: String,
    pub id: String,
    pub slug: String,
    pub name: String,
    pub created_at: String,
    pub updated_at: String,
}

pub fn now_timestamp() -> String {
    Utc::now().to_rfc3339()
}

pub fn make_entity_id(prefix: &str) -> String {
    format!("{}_{}", prefix, Utc::now().format("%Y%m%d%H%M%S%3f"))
}

pub fn slugify(value: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;

    for ch in value.trim().chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
            last_dash = false;
        } else if (ch.is_ascii_whitespace() || ch == '-' || ch == '_' || ch == '.') && !last_dash {
            out.push('-');
            last_dash = true;
        }
    }

    let trimmed = out.trim_matches('-');
    if trimmed.is_empty() {
        "untitled".to_string()
    } else {
        trimmed.to_string()
    }
}

pub fn unique_slug_for_dir(root: &Path, relative_dir: &str, base_slug: &str) -> String {
    let mut candidate = base_slug.to_string();
    let mut idx = 2;

    loop {
        let path = root.join(relative_dir).join(format!("{candidate}.md"));
        if !path.exists() {
            return candidate;
        }

        candidate = format!("{base_slug}-{idx}");
        idx += 1;
    }
}

pub fn render_npc_markdown(frontmatter: &NpcFrontmatter) -> Result<String, toml::ser::Error> {
    #[derive(Serialize)]
    struct Frontmatter<'a> {
        #[serde(rename = "type")]
        doc_type: &'a str,
        id: &'a str,
        slug: &'a str,
        name: &'a str,
        race: &'a str,
        sex: &'a str,
        location: &'a str,
        created_at: &'a str,
        updated_at: &'a str,
    }

    let fm = Frontmatter {
        doc_type: &frontmatter.doc_type,
        id: &frontmatter.id,
        slug: &frontmatter.slug,
        name: &frontmatter.name,
        race: &frontmatter.race,
        sex: &frontmatter.sex,
        location: &frontmatter.location,
        created_at: &frontmatter.created_at,
        updated_at: &frontmatter.updated_at,
    };

    let mut out = String::new();
    out.push_str("+++\n");
    out.push_str(&toml::to_string_pretty(&fm)?);
    out.push_str("+++\n\n");
    out.push_str("## Summary\n");
    out.push_str("Generated by runebound.sh.\n\n");
    out.push_str("## Notes\n");
    out.push_str("-\n");
    Ok(out)
}

pub fn render_location_markdown(
    frontmatter: &LocationFrontmatter,
) -> Result<String, toml::ser::Error> {
    #[derive(Serialize)]
    struct Frontmatter<'a> {
        #[serde(rename = "type")]
        doc_type: &'a str,
        id: &'a str,
        slug: &'a str,
        name: &'a str,
        created_at: &'a str,
        updated_at: &'a str,
    }

    let fm = Frontmatter {
        doc_type: &frontmatter.doc_type,
        id: &frontmatter.id,
        slug: &frontmatter.slug,
        name: &frontmatter.name,
        created_at: &frontmatter.created_at,
        updated_at: &frontmatter.updated_at,
    };

    let mut out = String::new();
    out.push_str("+++\n");
    out.push_str(&toml::to_string_pretty(&fm)?);
    out.push_str("+++\n\n");
    out.push_str("## Overview\n");
    out.push_str("-\n\n");
    out.push_str("## Notes\n");
    out.push_str("-\n");
    Ok(out)
}
