use std::path::Path;

use dnd_core::entity_store::EntityStore;
use dnd_core::npc::{
    DungeonFrontmatter, EventFrontmatter, FactionFrontmatter, GodFrontmatter, ItemFrontmatter,
    LocationFrontmatter, NpcFrontmatter, UNKNOWN_LOCATION, normalize_markdown_file_stem,
    now_timestamp, slugify, unique_slug_for_dir_with_ext,
};
use dnd_core::serialization::{carrying_to_db_text, exports_to_db_text, faction_list_to_db_text};
use serde::Serialize;

use crate::app_state::{
    AppState, DraftEnvelope, DungeonDraftSession, EventDraftSession, FactionDraftSession,
    GodDraftSession, ItemDraftSession, LocationDraftSession, NpcDraftSession,
};
use crate::repositories::db;
use crate::repositories::db::{
    DungeonRow, EventRow, FactionRow, GodRow, ItemRow, LocationRow, NpcRow,
};
use crate::services::ai_generation::LocationSeed;
use crate::services::entity_persistence_macros::impl_entity_persistence;
use crate::utils::{
    normalize_dungeon_tone, normalize_dungeon_topology, normalize_dungeon_twist, normalize_exports,
    normalize_faction_kind_type, normalize_god_alignment, normalize_god_rank,
    normalize_item_category, normalize_item_rarity, normalize_location_danger_level,
    normalize_location_kind_type, normalize_relative_path_for_storage, normalize_sex,
    normalize_unknown_list, normalize_unknown_text, validate_location_details,
};

pub struct EntityPersistenceService;

/// The common result of persisting any entity draft (was seven identical
/// `Save*DraftResult` structs).
#[derive(Debug, Clone, Serialize)]
pub struct SaveOutcome {
    pub id: String,
    pub slug: String,
    pub vault_path: String,
    pub created_at: String,
    pub updated_at: String,
}

impl EntityPersistenceService {
    /// Persist the active draft (TOML store + DB row + document index), routing to
    /// the per-kind save generated by [`impl_entity_persistence!`]. The typed draft
    /// carried by the [`DraftEnvelope`] is the input — no per-kind `Save*Input`.
    pub async fn save(
        &self,
        draft: &DraftEnvelope,
        state: &AppState,
    ) -> Result<SaveOutcome, String> {
        match draft {
            DraftEnvelope::Npc(draft) => save_npc_draft(draft, state).await,
            DraftEnvelope::Location(draft) => save_location_draft(draft, state).await,
            DraftEnvelope::Faction(draft) => save_faction_draft(draft, state).await,
            DraftEnvelope::Item(draft) => save_item_draft(draft, state).await,
            DraftEnvelope::Event(draft) => save_event_draft(draft, state).await,
            DraftEnvelope::God(draft) => save_god_draft(draft, state).await,
            DraftEnvelope::Dungeon(draft) => save_dungeon_draft(draft, state).await,
        }
    }
}

impl_entity_persistence! {
    save_fn: save_npc_draft,
    draft_ty: NpcDraftSession,
    binder: draft,
    frontmatter: NpcFrontmatter,
    row: NpcRow,
    dir: "npcs",
    kind: "npc",
    repo: npc_repo,
    store_save: save_npc,
    store_load: load_npc,
    store_delete: delete_npc,
    normalize: {
        let race = draft.race.trim();
        if race.is_empty() {
            return Err("npc race cannot be empty".to_string());
        }
        let race = race.to_string();
        let occupation = normalize_unknown_text(&draft.occupation);
        let sex = normalize_sex(&draft.sex)?;
        let age = normalize_unknown_text(&draft.age);
        let height = normalize_unknown_text(&draft.height);
        let weight_lbs = normalize_unknown_text(&draft.weight_lbs);
        let background = normalize_unknown_text(&draft.background);
        let want_need = normalize_unknown_text(&draft.want_need);
        let secret_obstacle = normalize_unknown_text(&draft.secret_obstacle);
        let carrying = normalize_unknown_list(draft.carrying.clone());
        let carrying_db = carrying_to_db_text(&carrying)?;
        let location = if draft.location.trim().is_empty() {
            UNKNOWN_LOCATION.to_string()
        } else {
            draft.location.trim().to_string()
        };
    },
    frontmatter_fields: {
        race: race.clone(),
        occupation: occupation.clone(),
        sex: sex.clone(),
        age: age.clone(),
        height: height.clone(),
        weight_lbs: weight_lbs.clone(),
        background: background.clone(),
        want_need: want_need.clone(),
        secret_obstacle: secret_obstacle.clone(),
        carrying: carrying.clone(),
        location: location.clone(),
    },
    row_fields: {
        race,
        occupation,
        sex,
        age,
        height,
        weight_lbs,
        background,
        want_need,
        secret_obstacle,
        carrying: carrying_db,
        location,
    },
}

impl_entity_persistence! {
    save_fn: save_location_draft,
    draft_ty: LocationDraftSession,
    binder: draft,
    frontmatter: LocationFrontmatter,
    row: LocationRow,
    dir: "locations",
    // Wizard-built drafts subfolder the readable `.md` by kind; one-shots (and any
    // non-wizard draft) pass "other" so they stay flat in `locations/`. The slug and
    // TOML store keep `dir` ("locations") — only the Obsidian path is reshaped.
    vault_dir: crate::services::ai_generation::location_dir_for_kind(
        "locations",
        if draft.wizard_subfoldered { &kind_type } else { "other" },
    ),
    kind: "location",
    repo: location_repo,
    store_save: save_location,
    store_load: load_location,
    store_delete: delete_location,
    normalize: {
        let name = draft.name.trim();
        let kind_type = normalize_location_kind_type(&draft.kind_type)?;
        let mut kind_custom = draft
            .kind_custom
            .clone()
            .map(|value| normalize_unknown_text(&value));
        if kind_type == "other" {
            if kind_custom
                .as_ref()
                .is_none_or(|value| value.trim().is_empty())
            {
                return Err("kind_custom is required when kind_type is other".to_string());
            }
        } else {
            kind_custom = None;
        }
        let visual_description = normalize_unknown_text(&draft.visual_description);
        let history_background = normalize_unknown_text(&draft.history_background);
        let exports = normalize_exports(draft.exports.clone());
        let tone = normalize_unknown_text(&draft.tone);
        let authority = normalize_unknown_text(&draft.authority);
        let danger_level = normalize_location_danger_level(&draft.danger_level)?;
        let current_tension = normalize_unknown_text(&draft.current_tension);
        // The containing-location anchor is an entity reference, not prose — keep it
        // empty when unset (the markdown/card omit it) rather than coercing "Unknown".
        let location = draft.location.trim().to_string();
        validate_location_details(&LocationSeed {
            name: name.to_string(),
            kind_type: kind_type.clone(),
            kind_custom: kind_custom.clone(),
            visual_description: visual_description.clone(),
            history_background: history_background.clone(),
            exports: exports.clone(),
            tone: tone.clone(),
            authority: authority.clone(),
            danger_level: danger_level.clone(),
            current_tension: current_tension.clone(),
        })?;
        let exports_db = exports_to_db_text(&exports)?;
    },
    frontmatter_fields: {
        kind_type: kind_type.clone(),
        kind_custom: kind_custom.clone(),
        visual_description: visual_description.clone(),
        history_background: history_background.clone(),
        exports: exports.clone(),
        tone: tone.clone(),
        authority: authority.clone(),
        danger_level: danger_level.clone(),
        current_tension: current_tension.clone(),
        location: location.clone(),
    },
    row_fields: {
        kind_type,
        kind_custom,
        visual_description,
        history_background,
        exports: exports_db,
        tone,
        authority,
        danger_level,
        current_tension,
        location,
    },
}

impl_entity_persistence! {
    save_fn: save_faction_draft,
    draft_ty: FactionDraftSession,
    binder: draft,
    frontmatter: FactionFrontmatter,
    row: FactionRow,
    dir: "factions",
    kind: "faction",
    repo: faction_repo,
    store_save: save_faction,
    store_load: load_faction,
    store_delete: delete_faction,
    normalize: {
        let kind_type = normalize_faction_kind_type(&draft.kind_type)?;
        let kind_custom = if kind_type == "other" {
            let value = draft
                .kind_custom
                .as_ref()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
                .ok_or_else(|| "kind_custom is required when kind_type is other".to_string())?;
            Some(value.to_string())
        } else {
            None
        };
        let public_description = normalize_unknown_text(&draft.public_description);
        let true_agenda = normalize_unknown_text(&draft.true_agenda);
        let methods = normalize_unknown_text(&draft.methods);
        let leadership = normalize_unknown_text(&draft.leadership);
        let headquarters = normalize_unknown_text(&draft.headquarters);
        let sphere_of_influence = normalize_unknown_text(&draft.sphere_of_influence);
        let resources_assets = normalize_unknown_list(draft.resources_assets.clone());
        let allies = normalize_unknown_list(draft.allies.clone());
        let rivals_enemies = normalize_unknown_list(draft.rivals_enemies.clone());
        let reputation = normalize_unknown_text(&draft.reputation);
        let current_tension = normalize_unknown_text(&draft.current_tension);
        let goals_short_term = normalize_unknown_list(draft.goals_short_term.clone());
        let goals_long_term = normalize_unknown_list(draft.goals_long_term.clone());
        let symbol_description = normalize_unknown_text(&draft.symbol_description);
        let resources_assets_db = faction_list_to_db_text(&resources_assets)?;
        let allies_db = faction_list_to_db_text(&allies)?;
        let rivals_db = faction_list_to_db_text(&rivals_enemies)?;
        let goals_short_db = faction_list_to_db_text(&goals_short_term)?;
        let goals_long_db = faction_list_to_db_text(&goals_long_term)?;
    },
    frontmatter_fields: {
        kind_type: kind_type.clone(),
        kind_custom: kind_custom.clone(),
        public_description: public_description.clone(),
        true_agenda: true_agenda.clone(),
        methods: methods.clone(),
        leadership: leadership.clone(),
        headquarters: headquarters.clone(),
        sphere_of_influence: sphere_of_influence.clone(),
        resources_assets: resources_assets.clone(),
        allies: allies.clone(),
        rivals_enemies: rivals_enemies.clone(),
        reputation: reputation.clone(),
        current_tension: current_tension.clone(),
        goals_short_term: goals_short_term.clone(),
        goals_long_term: goals_long_term.clone(),
        symbol_description: symbol_description.clone(),
    },
    row_fields: {
        kind_type,
        kind_custom,
        public_description,
        true_agenda,
        methods,
        leadership,
        headquarters,
        sphere_of_influence,
        resources_assets: resources_assets_db,
        allies: allies_db,
        rivals_enemies: rivals_db,
        reputation,
        current_tension,
        goals_short_term: goals_short_db,
        goals_long_term: goals_long_db,
        symbol_description,
    },
}

impl_entity_persistence! {
    save_fn: save_god_draft,
    draft_ty: GodDraftSession,
    binder: draft,
    frontmatter: GodFrontmatter,
    row: GodRow,
    dir: "gods",
    kind: "god",
    repo: god_repo,
    store_save: save_god,
    store_load: load_god,
    store_delete: delete_god,
    normalize: {
        let rank = normalize_god_rank(&draft.rank)?;
        let rank_custom = if rank == "other" {
            let value = draft
                .rank_custom
                .as_ref()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
                .ok_or_else(|| "rank_custom is required when rank is other".to_string())?;
            Some(value.to_string())
        } else {
            None
        };
        let alignment = normalize_god_alignment(&draft.alignment)?;
        let epithet = normalize_unknown_text(&draft.epithet);
        let domains = normalize_unknown_list(draft.domains.clone());
        let symbol = normalize_unknown_text(&draft.symbol);
        let appearance = normalize_unknown_text(&draft.appearance);
        let dogma = normalize_unknown_text(&draft.dogma);
        let realm = normalize_unknown_text(&draft.realm);
        let worshippers = normalize_unknown_text(&draft.worshippers);
        let clergy = normalize_unknown_text(&draft.clergy);
        let allies = normalize_unknown_list(draft.allies.clone());
        let rivals = normalize_unknown_list(draft.rivals.clone());
        let domains_db = faction_list_to_db_text(&domains)?;
        let allies_db = faction_list_to_db_text(&allies)?;
        let rivals_db = faction_list_to_db_text(&rivals)?;
    },
    frontmatter_fields: {
        epithet: epithet.clone(),
        rank: rank.clone(),
        rank_custom: rank_custom.clone(),
        alignment: alignment.clone(),
        domains: domains.clone(),
        symbol: symbol.clone(),
        appearance: appearance.clone(),
        dogma: dogma.clone(),
        realm: realm.clone(),
        worshippers: worshippers.clone(),
        clergy: clergy.clone(),
        allies: allies.clone(),
        rivals: rivals.clone(),
    },
    row_fields: {
        epithet,
        rank,
        rank_custom,
        alignment,
        domains: domains_db,
        symbol,
        appearance,
        dogma,
        realm,
        worshippers,
        clergy,
        allies: allies_db,
        rivals: rivals_db,
    },
}

impl_entity_persistence! {
    save_fn: save_dungeon_draft,
    draft_ty: DungeonDraftSession,
    binder: draft,
    frontmatter: DungeonFrontmatter,
    row: DungeonRow,
    dir: "dungeons",
    kind: "dungeon",
    repo: dungeon_repo,
    store_save: save_dungeon,
    store_load: load_dungeon,
    store_delete: delete_dungeon,
    normalize: {
        let location = normalize_unknown_text(&draft.location);
        let story = draft.story.trim().to_string();
        let premise = normalize_unknown_text(&draft.premise);
        let topology = normalize_dungeon_topology(&draft.topology)?;
        let tone = normalize_dungeon_tone(&draft.tone)?;
        let twist = normalize_dungeon_twist(&draft.twist)?;
        let beats = draft.beats.clone();
        let beats_json = serde_json::to_string(&beats)
            .map_err(|err| format!("failed to encode dungeon beats: {err}"))?;
    },
    frontmatter_fields: {
        location: location.clone(),
        story: story.clone(),
        premise: premise.clone(),
        topology: topology.clone(),
        tone: tone.clone(),
        twist: twist.clone(),
        beats: beats.clone(),
    },
    row_fields: {
        location,
        story,
        premise,
        topology,
        tone,
        twist,
        beats_json,
    },
}

impl_entity_persistence! {
    save_fn: save_item_draft,
    draft_ty: ItemDraftSession,
    binder: draft,
    frontmatter: ItemFrontmatter,
    row: ItemRow,
    dir: "items",
    kind: "item",
    repo: item_repo,
    store_save: save_item,
    store_load: load_item,
    store_delete: delete_item,
    normalize: {
        let category = normalize_item_category(&draft.category)?;
        let rarity = normalize_item_rarity(&draft.rarity)?;
        let attunement = normalize_unknown_text(&draft.attunement);
        let materials = normalize_unknown_list(draft.materials.clone());
        let materials_db = faction_list_to_db_text(&materials)?;
        let appearance = normalize_unknown_text(&draft.appearance);
        let abilities = normalize_unknown_text(&draft.abilities);
        let drawbacks = normalize_unknown_text(&draft.drawbacks);
        let history = normalize_unknown_text(&draft.history);
        let value = normalize_unknown_text(&draft.value);
        let location = normalize_unknown_text(&draft.location);
    },
    frontmatter_fields: {
        category: category.clone(),
        rarity: rarity.clone(),
        attunement: attunement.clone(),
        materials: materials.clone(),
        appearance: appearance.clone(),
        abilities: abilities.clone(),
        drawbacks: drawbacks.clone(),
        history: history.clone(),
        value: value.clone(),
        location: location.clone(),
    },
    row_fields: {
        category,
        rarity,
        attunement,
        materials: materials_db,
        appearance,
        abilities,
        drawbacks,
        history,
        value,
        location,
    },
}

impl_entity_persistence! {
    save_fn: save_event_draft,
    draft_ty: EventDraftSession,
    binder: draft,
    frontmatter: EventFrontmatter,
    row: EventRow,
    dir: "events",
    kind: "event",
    repo: event_repo,
    store_save: save_event,
    store_load: load_event,
    store_delete: delete_event,
    normalize: {
        // Events are narrative-only: the body is stored verbatim (just trimmed),
        // with none of the field normalization the structured entities apply.
        let body = draft.body.trim().to_string();
        if body.is_empty() {
            return Err("event body cannot be empty".to_string());
        }
    },
    frontmatter_fields: {
        body: body.clone(),
    },
    row_fields: {
        body,
    },
}

/// A reference to the existing DB row for an entity being re-saved, normalized to
/// the fields the shared save helpers need.
struct ExistingRef<'a> {
    slug: &'a str,
    vault_path: &'a str,
}

/// Resolve the canonical slug for a save: keep the current slug when the name
/// hasn't changed, otherwise mint a fresh unique slug under `dir`.
fn resolve_slug(root: &Path, dir: &str, existing_slug: Option<&str>, name: &str) -> String {
    let base_slug = slugify(name);
    match existing_slug {
        Some(slug) if slug == base_slug => slug.to_string(),
        _ => unique_slug_for_dir_with_ext(root, dir, &base_slug, "toml"),
    }
}

/// Resolve the readable vault (markdown) path for a save, plus the old vault path
/// whose document-index entry should be retired (if the readable name changed).
///
/// The path is always derived from the current `name`: reuse the existing path
/// when it already matches that readable name, otherwise compute a fresh unique
/// readable path (and report the old one for retirement). Deriving from `name`
/// rather than a stored draft path is what makes a rename/reroll re-file the
/// entity under its new name. The retirement is *returned* rather than performed
/// here so the caller can fold it into the same transaction as the row/index
/// upsert (P6.1).
///
/// `dir` is the folder a *new* row lands in. An *existing* row keeps the folder it
/// already lives in (derived from its current path's parent), so a re-save never
/// thrashes a subfoldered location back to flat (nor a flat one-shot into a
/// subfolder when its kind is later edited). For the six entities that never nest,
/// `parent_dir_of` returns exactly `dir`, so behavior is unchanged.
async fn resolve_vault_path(
    document_repo: &dyn crate::repositories::DocumentRepository,
    database: &db::Database,
    dir: &str,
    name: &str,
    existing: Option<ExistingRef<'_>>,
) -> Result<(String, Option<String>), String> {
    match existing {
        Some(current) => {
            let dir = parent_dir_of(current.vault_path).unwrap_or(dir);
            let readable =
                unique_readable_vault_path(document_repo, database, dir, name, Some(current.slug))
                    .await?;
            if normalize_relative_path_for_storage(current.vault_path)
                == normalize_relative_path_for_storage(&readable)
            {
                Ok((current.vault_path.to_string(), None))
            } else {
                Ok((readable, Some(current.vault_path.to_string())))
            }
        }
        None => Ok((
            unique_readable_vault_path(document_repo, database, dir, name, None).await?,
            None,
        )),
    }
}

/// The directory portion of a relative vault path: `locations/sites/Foo.md` ->
/// `Some("locations/sites")`, `locations/Foo.md` -> `Some("locations")`, a bare
/// `Foo.md` -> `None`. Used to keep an existing note in its current folder on re-save.
fn parent_dir_of(vault_path: &str) -> Option<&str> {
    let p = vault_path.trim_end_matches('/');
    p.rfind('/').map(|i| &p[..i])
}

/// Compute a unique `dir/Name.md` path, disambiguating collisions with a numeric
/// suffix unless the colliding entry is the entity we're saving (`current_slug`).
pub(crate) async fn unique_readable_vault_path(
    document_repo: &dyn crate::repositories::DocumentRepository,
    database: &db::Database,
    relative_dir: &str,
    display_name: &str,
    current_slug: Option<&str>,
) -> Result<String, String> {
    let base = normalize_markdown_file_stem(display_name);
    let mut candidate = format!("{relative_dir}/{base}.md");
    let mut idx = 2;
    while let Some(found_slug) = document_repo
        .find_by_vault_path(database, &candidate)
        .await?
    {
        if current_slug == Some(found_slug.as_str()) {
            return Ok(candidate);
        }
        candidate = format!("{relative_dir}/{base} {idx}.md");
        idx += 1;
    }
    Ok(candidate)
}

#[cfg(test)]
mod tests {
    use super::{ExistingRef, parent_dir_of, resolve_vault_path};
    use crate::repositories::ProdDocumentRepository;
    use dnd_core::db::{Database, init_database_at_path};
    use std::sync::atomic::{AtomicUsize, Ordering};

    #[test]
    fn parent_dir_of_extracts_folder_or_none_for_flat() {
        assert_eq!(
            parent_dir_of("locations/sites/Foo.md"),
            Some("locations/sites")
        );
        assert_eq!(parent_dir_of("locations/Foo.md"), Some("locations"));
        assert_eq!(parent_dir_of("Foo.md"), None);
        // Trailing slash is trimmed before splitting.
        assert_eq!(parent_dir_of("locations/sites/"), Some("locations"));
    }

    async fn temp_db() -> Database {
        static COUNTER: AtomicUsize = AtomicUsize::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "dnd_persist_test_{}_{}.sqlite",
            std::process::id(),
            n
        ));
        let _ = std::fs::remove_file(&path);
        init_database_at_path(&path).await.expect("init test db")
    }

    #[tokio::test]
    async fn new_wizard_row_lands_in_the_kind_subfolder() {
        let db = temp_db().await;
        let repo = ProdDocumentRepository;
        // The caller (macro) passes the subfoldered dir for a wizard kind.
        let (path, retire) = resolve_vault_path(&repo, &db, "locations/sites", "Mirecairn", None)
            .await
            .unwrap();
        assert_eq!(path, "locations/sites/Mirecairn.md");
        assert!(retire.is_none());
    }

    #[tokio::test]
    async fn new_one_shot_row_stays_flat() {
        let db = temp_db().await;
        let repo = ProdDocumentRepository;
        // One-shots pass the flat dir ("other" => flat at the call site).
        let (path, retire) = resolve_vault_path(&repo, &db, "locations", "Mirecairn", None)
            .await
            .unwrap();
        assert_eq!(path, "locations/Mirecairn.md");
        assert!(retire.is_none());
    }

    #[tokio::test]
    async fn existing_subfoldered_note_renamed_stays_in_its_subfolder() {
        let db = temp_db().await;
        let repo = ProdDocumentRepository;
        let existing = ExistingRef {
            slug: "mirecairn",
            vault_path: "locations/sites/Mirecairn.md",
        };
        let (path, retire) =
            resolve_vault_path(&repo, &db, "locations/sites", "Deepmire", Some(existing))
                .await
                .unwrap();
        // Re-filed under the new name, still inside sites/; old path retired.
        assert_eq!(path, "locations/sites/Deepmire.md");
        assert_eq!(retire.as_deref(), Some("locations/sites/Mirecairn.md"));
    }

    #[tokio::test]
    async fn existing_flat_note_renamed_stays_flat() {
        let db = temp_db().await;
        let repo = ProdDocumentRepository;
        let existing = ExistingRef {
            slug: "greenhollow",
            vault_path: "locations/Greenhollow.md",
        };
        let (path, retire) =
            resolve_vault_path(&repo, &db, "locations", "Mossford", Some(existing))
                .await
                .unwrap();
        assert_eq!(path, "locations/Mossford.md");
        assert_eq!(retire.as_deref(), Some("locations/Greenhollow.md"));
    }

    #[tokio::test]
    async fn kind_edit_of_existing_note_does_not_refolder() {
        let db = temp_db().await;
        let repo = ProdDocumentRepository;
        // Existing flat note; its kind is now a structured one, so the macro passes a
        // subfoldered dir. The folder must still come from the current path -> flat,
        // and with the same name there is nothing to retire.
        let existing = ExistingRef {
            slug: "greenhollow",
            vault_path: "locations/Greenhollow.md",
        };
        let (path, retire) =
            resolve_vault_path(&repo, &db, "locations/sites", "Greenhollow", Some(existing))
                .await
                .unwrap();
        assert_eq!(path, "locations/Greenhollow.md");
        assert!(retire.is_none());
    }
}
