use std::path::Path;

use dnd_core::entity_store::EntityStore;
use dnd_core::npc::{
    DungeonFrontmatter, EventFrontmatter, FactionFrontmatter, GodFrontmatter, ItemFrontmatter,
    LocationFrontmatter, NpcFrontmatter, UNKNOWN_LOCATION, normalize_markdown_file_stem,
    now_timestamp, slugify, unique_slug_for_dir_with_ext,
};
use dnd_core::serialization::{carrying_to_db_text, exports_to_db_text, faction_list_to_db_text};
use serde::Serialize;

use crate::app_state::{
    AppState, DraftEnvelope, DungeonDraftSession, EventDraftSession, FactionDraftSession,
    GodDraftSession, ItemDraftSession, LocationDraftSession, NpcDraftSession,
};
use crate::repositories::db;
use crate::repositories::db::{
    DungeonRow, EventRow, FactionRow, GodRow, ItemRow, LocationRow, NpcRow,
};
use crate::services::ai_generation::LocationSeed;
use crate::services::entity_persistence_macros::impl_entity_persistence;
use crate::utils::{
    normalize_dungeon_tone, normalize_dungeon_topology, normalize_dungeon_twist, normalize_exports,
    normalize_faction_kind_type, normalize_god_alignment, normalize_god_rank,
    normalize_item_category, normalize_item_rarity, normalize_location_danger_level,
    normalize_location_kind_type, normalize_relative_path_for_storage, normalize_sex,
    normalize_unknown_list, normalize_unknown_text, validate_location_details,
};

pub struct EntityPersistenceService;

/// The common result of persisting any entity draft (was seven identical
/// `Save*DraftResult` structs).
#[derive(Debug, Clone, Serialize)]
pub struct SaveOutcome {
    pub id: String,
    pub slug: String,
    pub vault_path: String,
    pub created_at: String,
    pub updated_at: String,
}

impl EntityPersistenceService {
    /// Persist the active draft (TOML store + DB row + document index), routing to
    /// the per-kind save generated by [`impl_entity_persistence!`]. The typed draft
    /// carried by the [`DraftEnvelope`] is the input — no per-kind `Save*Input`.
    pub async fn save(
        &self,
        draft: &DraftEnvelope,
        state: &AppState,
    ) -> Result<SaveOutcome, String> {
        match draft {
            DraftEnvelope::Npc(draft) => save_npc_draft(draft, state).await,
            DraftEnvelope::Location(draft) => save_location_draft(draft, state).await,
            DraftEnvelope::Faction(draft) => save_faction_draft(draft, state).await,
            DraftEnvelope::Item(draft) => save_item_draft(draft, state).await,
            DraftEnvelope::Event(draft) => save_event_draft(draft, state).await,
            DraftEnvelope::God(draft) => save_god_draft(draft, state).await,
            DraftEnvelope::Dungeon(draft) => save_dungeon_draft(draft, state).await,
        }
    }
}

impl_entity_persistence! {
    save_fn: save_npc_draft,
    draft_ty: NpcDraftSession,
    binder: draft,
    frontmatter: NpcFrontmatter,
    row: NpcRow,
    dir: "npcs",
    kind: "npc",
    repo: npc_repo,
    store_save: save_npc,
    store_load: load_npc,
    store_delete: delete_npc,
    requested_vault_path: None,
    normalize: {
        let race = draft.race.trim();
        if race.is_empty() {
            return Err("npc race cannot be empty".to_string());
        }
        let race = race.to_string();
        let occupation = normalize_unknown_text(&draft.occupation);
        let sex = normalize_sex(&draft.sex)?;
        let age = normalize_unknown_text(&draft.age);
        let height = normalize_unknown_text(&draft.height);
        let weight_lbs = normalize_unknown_text(&draft.weight_lbs);
        let background = normalize_unknown_text(&draft.background);
        let want_need = normalize_unknown_text(&draft.want_need);
        let secret_obstacle = normalize_unknown_text(&draft.secret_obstacle);
        let carrying = normalize_unknown_list(draft.carrying.clone());
        let carrying_db = carrying_to_db_text(&carrying)?;
        let location = if draft.location.trim().is_empty() {
            UNKNOWN_LOCATION.to_string()
        } else {
            draft.location.trim().to_string()
        };
    },
    frontmatter_fields: {
        race: race.clone(),
        occupation: occupation.clone(),
        sex: sex.clone(),
        age: age.clone(),
        height: height.clone(),
        weight_lbs: weight_lbs.clone(),
        background: background.clone(),
        want_need: want_need.clone(),
        secret_obstacle: secret_obstacle.clone(),
        carrying: carrying.clone(),
        location: location.clone(),
    },
    row_fields: {
        race,
        occupation,
        sex,
        age,
        height,
        weight_lbs,
        background,
        want_need,
        secret_obstacle,
        carrying: carrying_db,
        location,
    },
}

impl_entity_persistence! {
    save_fn: save_location_draft,
    draft_ty: LocationDraftSession,
    binder: draft,
    frontmatter: LocationFrontmatter,
    row: LocationRow,
    dir: "locations",
    kind: "location",
    repo: location_repo,
    store_save: save_location,
    store_load: load_location,
    store_delete: delete_location,
    requested_vault_path: Some(draft.vault_path.as_str()),
    normalize: {
        let name = draft.name.trim();
        let kind_type = normalize_location_kind_type(&draft.kind_type)?;
        let mut kind_custom = draft
            .kind_custom
            .clone()
            .map(|value| normalize_unknown_text(&value));
        if kind_type == "other" {
            if kind_custom
                .as_ref()
                .is_none_or(|value| value.trim().is_empty())
            {
                return Err("kind_custom is required when kind_type is other".to_string());
            }
        } else {
            kind_custom = None;
        }
        let visual_description = normalize_unknown_text(&draft.visual_description);
        let history_background = normalize_unknown_text(&draft.history_background);
        let exports = normalize_exports(draft.exports.clone());
        let tone = normalize_unknown_text(&draft.tone);
        let authority = normalize_unknown_text(&draft.authority);
        let danger_level = normalize_location_danger_level(&draft.danger_level)?;
        let current_tension = normalize_unknown_text(&draft.current_tension);
        validate_location_details(&LocationSeed {
            name: name.to_string(),
            kind_type: kind_type.clone(),
            kind_custom: kind_custom.clone(),
            visual_description: visual_description.clone(),
            history_background: history_background.clone(),
            exports: exports.clone(),
            tone: tone.clone(),
            authority: authority.clone(),
            danger_level: danger_level.clone(),
            current_tension: current_tension.clone(),
        })?;
        let exports_db = exports_to_db_text(&exports)?;
    },
    frontmatter_fields: {
        kind_type: kind_type.clone(),
        kind_custom: kind_custom.clone(),
        visual_description: visual_description.clone(),
        history_background: history_background.clone(),
        exports: exports.clone(),
        tone: tone.clone(),
        authority: authority.clone(),
        danger_level: danger_level.clone(),
        current_tension: current_tension.clone(),
    },
    row_fields: {
        kind_type,
        kind_custom,
        visual_description,
        history_background,
        exports: exports_db,
        tone,
        authority,
        danger_level,
        current_tension,
    },
}

impl_entity_persistence! {
    save_fn: save_faction_draft,
    draft_ty: FactionDraftSession,
    binder: draft,
    frontmatter: FactionFrontmatter,
    row: FactionRow,
    dir: "factions",
    kind: "faction",
    repo: faction_repo,
    store_save: save_faction,
    store_load: load_faction,
    store_delete: delete_faction,
    requested_vault_path: Some(draft.vault_path.as_str()),
    normalize: {
        let kind_type = normalize_faction_kind_type(&draft.kind_type)?;
        let kind_custom = if kind_type == "other" {
            let value = draft
                .kind_custom
                .as_ref()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
                .ok_or_else(|| "kind_custom is required when kind_type is other".to_string())?;
            Some(value.to_string())
        } else {
            None
        };
        let public_description = normalize_unknown_text(&draft.public_description);
        let true_agenda = normalize_unknown_text(&draft.true_agenda);
        let methods = normalize_unknown_text(&draft.methods);
        let leadership = normalize_unknown_text(&draft.leadership);
        let headquarters = normalize_unknown_text(&draft.headquarters);
        let sphere_of_influence = normalize_unknown_text(&draft.sphere_of_influence);
        let resources_assets = normalize_unknown_text(&draft.resources_assets);
        let allies = normalize_unknown_list(draft.allies.clone());
        let rivals_enemies = normalize_unknown_list(draft.rivals_enemies.clone());
        let reputation = normalize_unknown_text(&draft.reputation);
        let current_tension = normalize_unknown_text(&draft.current_tension);
        let goals_short_term = normalize_unknown_list(draft.goals_short_term.clone());
        let goals_long_term = normalize_unknown_list(draft.goals_long_term.clone());
        let symbol_description = normalize_unknown_text(&draft.symbol_description);
        let allies_db = faction_list_to_db_text(&allies)?;
        let rivals_db = faction_list_to_db_text(&rivals_enemies)?;
        let goals_short_db = faction_list_to_db_text(&goals_short_term)?;
        let goals_long_db = faction_list_to_db_text(&goals_long_term)?;
    },
    frontmatter_fields: {
        kind_type: kind_type.clone(),
        kind_custom: kind_custom.clone(),
        public_description: public_description.clone(),
        true_agenda: true_agenda.clone(),
        methods: methods.clone(),
        leadership: leadership.clone(),
        headquarters: headquarters.clone(),
        sphere_of_influence: sphere_of_influence.clone(),
        resources_assets: resources_assets.clone(),
        allies: allies.clone(),
        rivals_enemies: rivals_enemies.clone(),
        reputation: reputation.clone(),
        current_tension: current_tension.clone(),
        goals_short_term: goals_short_term.clone(),
        goals_long_term: goals_long_term.clone(),
        symbol_description: symbol_description.clone(),
    },
    row_fields: {
        kind_type,
        kind_custom,
        public_description,
        true_agenda,
        methods,
        leadership,
        headquarters,
        sphere_of_influence,
        resources_assets,
        allies: allies_db,
        rivals_enemies: rivals_db,
        reputation,
        current_tension,
        goals_short_term: goals_short_db,
        goals_long_term: goals_long_db,
        symbol_description,
    },
}

impl_entity_persistence! {
    save_fn: save_god_draft,
    draft_ty: GodDraftSession,
    binder: draft,
    frontmatter: GodFrontmatter,
    row: GodRow,
    dir: "gods",
    kind: "god",
    repo: god_repo,
    store_save: save_god,
    store_load: load_god,
    store_delete: delete_god,
    requested_vault_path: Some(draft.vault_path.as_str()),
    normalize: {
        let rank = normalize_god_rank(&draft.rank)?;
        let rank_custom = if rank == "other" {
            let value = draft
                .rank_custom
                .as_ref()
                .map(|value| value.trim())
                .filter(|value| !value.is_empty())
                .ok_or_else(|| "rank_custom is required when rank is other".to_string())?;
            Some(value.to_string())
        } else {
            None
        };
        let alignment = normalize_god_alignment(&draft.alignment)?;
        let epithet = normalize_unknown_text(&draft.epithet);
        let domains = normalize_unknown_list(draft.domains.clone());
        let symbol = normalize_unknown_text(&draft.symbol);
        let appearance = normalize_unknown_text(&draft.appearance);
        let dogma = normalize_unknown_text(&draft.dogma);
        let realm = normalize_unknown_text(&draft.realm);
        let worshippers = normalize_unknown_text(&draft.worshippers);
        let clergy = normalize_unknown_text(&draft.clergy);
        let allies = normalize_unknown_list(draft.allies.clone());
        let rivals = normalize_unknown_list(draft.rivals.clone());
        let domains_db = faction_list_to_db_text(&domains)?;
        let allies_db = faction_list_to_db_text(&allies)?;
        let rivals_db = faction_list_to_db_text(&rivals)?;
    },
    frontmatter_fields: {
        epithet: epithet.clone(),
        rank: rank.clone(),
        rank_custom: rank_custom.clone(),
        alignment: alignment.clone(),
        domains: domains.clone(),
        symbol: symbol.clone(),
        appearance: appearance.clone(),
        dogma: dogma.clone(),
        realm: realm.clone(),
        worshippers: worshippers.clone(),
        clergy: clergy.clone(),
        allies: allies.clone(),
        rivals: rivals.clone(),
    },
    row_fields: {
        epithet,
        rank,
        rank_custom,
        alignment,
        domains: domains_db,
        symbol,
        appearance,
        dogma,
        realm,
        worshippers,
        clergy,
        allies: allies_db,
        rivals: rivals_db,
    },
}

impl_entity_persistence! {
    save_fn: save_dungeon_draft,
    draft_ty: DungeonDraftSession,
    binder: draft,
    frontmatter: DungeonFrontmatter,
    row: DungeonRow,
    dir: "dungeons",
    kind: "dungeon",
    repo: dungeon_repo,
    store_save: save_dungeon,
    store_load: load_dungeon,
    store_delete: delete_dungeon,
    requested_vault_path: Some(draft.vault_path.as_str()),
    normalize: {
        let location = normalize_unknown_text(&draft.location);
        let story = draft.story.trim().to_string();
        let premise = normalize_unknown_text(&draft.premise);
        let topology = normalize_dungeon_topology(&draft.topology)?;
        let tone = normalize_dungeon_tone(&draft.tone)?;
        let twist = normalize_dungeon_twist(&draft.twist)?;
        let beats = draft.beats.clone();
        let beats_json = serde_json::to_string(&beats)
            .map_err(|err| format!("failed to encode dungeon beats: {err}"))?;
    },
    frontmatter_fields: {
        location: location.clone(),
        story: story.clone(),
        premise: premise.clone(),
        topology: topology.clone(),
        tone: tone.clone(),
        twist: twist.clone(),
        beats: beats.clone(),
    },
    row_fields: {
        location,
        story,
        premise,
        topology,
        tone,
        twist,
        beats_json,
    },
}

impl_entity_persistence! {
    save_fn: save_item_draft,
    draft_ty: ItemDraftSession,
    binder: draft,
    frontmatter: ItemFrontmatter,
    row: ItemRow,
    dir: "items",
    kind: "item",
    repo: item_repo,
    store_save: save_item,
    store_load: load_item,
    store_delete: delete_item,
    requested_vault_path: None,
    normalize: {
        let category = normalize_item_category(&draft.category)?;
        let rarity = normalize_item_rarity(&draft.rarity)?;
        let attunement = normalize_unknown_text(&draft.attunement);
        let materials = normalize_unknown_list(draft.materials.clone());
        let materials_db = faction_list_to_db_text(&materials)?;
        let appearance = normalize_unknown_text(&draft.appearance);
        let abilities = normalize_unknown_text(&draft.abilities);
        let drawbacks = normalize_unknown_text(&draft.drawbacks);
        let history = normalize_unknown_text(&draft.history);
        let value = normalize_unknown_text(&draft.value);
        let location = normalize_unknown_text(&draft.location);
    },
    frontmatter_fields: {
        category: category.clone(),
        rarity: rarity.clone(),
        attunement: attunement.clone(),
        materials: materials.clone(),
        appearance: appearance.clone(),
        abilities: abilities.clone(),
        drawbacks: drawbacks.clone(),
        history: history.clone(),
        value: value.clone(),
        location: location.clone(),
    },
    row_fields: {
        category,
        rarity,
        attunement,
        materials: materials_db,
        appearance,
        abilities,
        drawbacks,
        history,
        value,
        location,
    },
}

impl_entity_persistence! {
    save_fn: save_event_draft,
    draft_ty: EventDraftSession,
    binder: draft,
    frontmatter: EventFrontmatter,
    row: EventRow,
    dir: "events",
    kind: "event",
    repo: event_repo,
    store_save: save_event,
    store_load: load_event,
    store_delete: delete_event,
    requested_vault_path: None,
    normalize: {
        // Events are narrative-only: the body is stored verbatim (just trimmed),
        // with none of the field normalization the structured entities apply.
        let body = draft.body.trim().to_string();
        if body.is_empty() {
            return Err("event body cannot be empty".to_string());
        }
    },
    frontmatter_fields: {
        body: body.clone(),
    },
    row_fields: {
        body,
    },
}

/// A reference to the existing DB row for an entity being re-saved, normalized to
/// the fields the shared save helpers need.
struct ExistingRef<'a> {
    slug: &'a str,
    vault_path: &'a str,
}

/// Resolve the canonical slug for a save: keep the current slug when the name
/// hasn't changed, otherwise mint a fresh unique slug under `dir`.
fn resolve_slug(root: &Path, dir: &str, existing_slug: Option<&str>, name: &str) -> String {
    let base_slug = slugify(name);
    match existing_slug {
        Some(slug) if slug == base_slug => slug.to_string(),
        _ => unique_slug_for_dir_with_ext(root, dir, &base_slug, "toml"),
    }
}

/// Resolve the readable vault (markdown) path for a save.
///
/// Precedence: an explicit `requested` path wins; otherwise reuse the existing
/// path when it already matches the readable name, else compute a fresh unique
/// readable path (retiring the old document-index entry on a rename).
async fn resolve_vault_path(
    document_repo: &dyn crate::repositories::DocumentRepository,
    database: &db::Database,
    dir: &str,
    name: &str,
    existing: Option<ExistingRef<'_>>,
    requested: Option<&str>,
) -> Result<String, String> {
    if let Some(requested) = requested {
        let normalized = normalize_relative_path_for_storage(requested.trim());
        if !normalized.is_empty() {
            return Ok(normalized);
        }
    }

    match existing {
        Some(current) => {
            let readable =
                unique_readable_vault_path(document_repo, database, dir, name, Some(current.slug))
                    .await?;
            if normalize_relative_path_for_storage(current.vault_path)
                == normalize_relative_path_for_storage(&readable)
            {
                Ok(current.vault_path.to_string())
            } else {
                document_repo
                    .delete_by_vault_path(database, current.vault_path)
                    .await?;
                Ok(readable)
            }
        }
        None => unique_readable_vault_path(document_repo, database, dir, name, None).await,
    }
}

/// Compute a unique `dir/Name.md` path, disambiguating collisions with a numeric
/// suffix unless the colliding entry is the entity we're saving (`current_slug`).
async fn unique_readable_vault_path(
    document_repo: &dyn crate::repositories::DocumentRepository,
    database: &db::Database,
    relative_dir: &str,
    display_name: &str,
    current_slug: Option<&str>,
) -> Result<String, String> {
    let base = normalize_markdown_file_stem(display_name);
    let mut candidate = format!("{relative_dir}/{base}.md");
    let mut idx = 2;
    while let Some(found_slug) = document_repo
        .find_by_vault_path(database, &candidate)
        .await?
    {
        if current_slug == Some(found_slug.as_str()) {
            return Ok(candidate);
        }
        candidate = format!("{relative_dir}/{base} {idx}.md");
        idx += 1;
    }
    Ok(candidate)
}
